### ISSUE TITLE
Enable experimental features runtime

### ISSUE THREAD

**Issue by sagikazarmark** [spf13/viper#1721]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Consumers may want to enable experimental features runtime. Although it may not always be possible, it should be doable for the most part.

### Proposed Solution

Introduce a new API to enable feature flags in Viper.

Something like:

```go
v := viper.New(viper.Enable("bind-struct"))
```

The nice thing about this API is that it's generic and it doesn't necessarily break once an experiment is rolled out as a fully functional feature.

The counterpart of `Enable` should be `Disable`, so users can go back to the old behavior while it's still available.

### Alternatives Considered

Other potential names:

- `EnableFlag`/`DisableFlag`
- `EnableExperiment`/`DisableExperiment`
- `Enable(Experimental)Feature`/`Disable(Experimental)Feature`

### Additional Information

Came up in https://github.com/spf13/viper/issues/1706#issuecomment-1858515373

**Comment by mazenharake** [comment]
imho, I think I would prefer `viper.New(viper.EnableBindStruct(), ...)`. I would also reckon it is easier to maintain since as more features are released then the `viper.Enable("...")` could become bloated. Since this is going to become a part of the API then it is clearer to know what Options there are by simply looking at the exported Options rather than to look up a string in the documentation.

just my 2 cents, either would be fine though.
