### ISSUE TITLE
ReadConfig(in io.Reader) does not Actually ReadConfig

### ISSUE THREAD

**Issue by dp1140a** [spf13/viper#1784]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.18.2

### Go Version

1.22

### Config Source

Files

### Format

TOML

### Code reproducing the issue

```go
/**
testdata/good_config.toml is a good toml file.
Viper sees it initially
**/
f, err := os.Open("testdata/good_config.toml")
if err != nil {
   assert.Fail(suite.T(), err.Error())
}
err = viper.ReadConfig(f)
if err != nil {
  assert.Fail(suite.T(), err.Error())
}
```

### Expected Behavior

should read the config.  When I print the config I expect the contents of the initial file.  but I get {}

### Actual Behavior

Return an empty config

### Additional Information

Did some initial debugging on this.

![shot1](https://github.com/spf13/viper/assets/5685054/421544d2-609f-4d74-a242-fff01c73100f)
At this point all is well.

![shot2](https://github.com/spf13/viper/assets/5685054/5fd1a2d3-fb02-4deb-868b-93c1665ff206)
Here is where things start to hinky

![shot3](https://github.com/spf13/viper/assets/5685054/1b6c99fe-dbbf-4a0f-b8d1-8e9a01e3bc10)
Still dont have a file tto read? Ok says Viper Ill try to find the config file . . . But wait!

![shot4](https://github.com/spf13/viper/assets/5685054/f900dd87-1be4-4352-9599-252e3450abc2)
Here you can see that configPath has never been set. It still has not set the configFile or pconfigPath despite asking for a file reader that has the name and path of the file. The reult is that it cant find the config file and fails.

BUT!!!
This code works:
```go
file := "testdata/good_config.toml"
viper.SetConfigName(strings.TrimSuffix(filepath.Base(file), filepath.Ext(file)))
viper.SetConfigType("toml")
viper.AddConfigPath(filepath.Dir(file))
f, err := os.Open(file)
if err != nil {
   assert.Fail(suite.T(), err.Error())
}
err = viper.ReadConfig(f)
if err != nil {
  assert.Fail(suite.T(), err.Error())
}
```

`So why would I go through all that trouble to use `ReadConfig(f) ` when I could just go through the same trouble and use ReadInConfig()`?

Seems like `ReadConfig(f)` should just ReadConfig from `f`

**Comment by mazenharake** [comment]
This seems to come up as a consequence of not specifying the config type. If you read in a file it still needs to be interpreted in some way and since the config type has not been set then `getConfigType()` resorts to trying to find the file instead and inferring the config type from the file extension. This is (probably) why your working example is successful.

See https://github.com/spf13/viper/blob/master/viper.go#L2218

I'll admit it is quirky behavior... perhaps adding a default case here https://github.com/spf13/viper/blob/master/viper.go#L1804 and retur an error would be more suitable since the function assumes that a config type has been set either explicitly or by using `ReadInConfig()`

Either way, using `SetConfigType` should resolve this issue?

**Comment by sagikazarmark** [comment]
I believe @mazenharake is correct.

**Comment by sagikazarmark** [comment]
Added a check that returns an error when no config type is set. In the future it might make more sense to introduce an option to specify the type.
