### ISSUE TITLE
After viper.Set(key, value)+viper.WriteConfig() ,  viper.WatchConfig()  cannot update the value of viper.Get()

### ISSUE THREAD

**Issue by LuSrackhall** [spf13/viper#1904]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.19.0

### Go Version

1.22.0

### Config Source

Files

### Format

JSON

### Expected Behavior

It can reflect the real situation in the configuration file, rather than obtaining the 'viper' in memory The value covered by Set().

### Actual Behavior

After viper.Set(key, value)+viper.WriteConfig() ,  When I manually modify the configuration file, viper.WatchConfig()  cannot update the value of viper.Get()

**Comment by FaheemuddinKhan** [comment]
@LuSrackhall 
Thank you for reporting this issue!

After reviewing the behavior, it appears that this is actually the expected behavior of the Viper library.

### Explanation:

When you use `viper.Set(key, value)`, the value is stored in the override register. According to the documentation:

```go
// Set sets the value for the key in the override register.
// Set is case-insensitive for a key.
// Will be used instead of values obtained via
// flags, config file, ENV, default, or key/value store.
```

This means that the value set via viper.Set() takes precedence over all other sources, including environment variables, configuration files, defaults, and so on.

Regarding viper.WatchConfig():
Even though viper.WatchConfig() is set up to monitor changes to the configuration file, any key that has been set via viper.Set() will always return the overridden value, regardless of the changes made in the configuration file. This is by design, as the override register has the highest priority.

If you need viper.Get() to reflect the changes from the configuration file, you may need to avoid using viper.Set() for those keys, or manually reset the value with viper.Set(key, nil) before fetching the updated value.

I hope this clarifies the situation. Let me know if you have any further questions!

**Comment by LuSrackhall** [comment]
Thank you for your response and help. This answer indeed solved the practical problem I was facing.

Before closing the question, please allow me to ask one more question:

After using viper.Set(key, nil), will it affect the speed of subsequent viper.Get(key) retrievals?
Maybe this question is unnecessary, but my understanding of Viper is too superficial. Many times, I can only verify some incorrect guesses through comparison and elimination methods.

Thank you again for your help!!!

**Comment by FaheemuddinKhan** [comment]
Thank you for your response and for allowing me to clarify further!

## Regarding Your Question

Using viper.Set(key, nil) removes the key from the overrides register, so viper.Get(key) will then check other sources like flags, environment variables, and the config file.

Theoretically, there is a slight overhead since Viper still checks the overrides first, but in practice, the difference is negligible. Viper works primarily with in-memory data, so even though it checks multiple sources, this happens quickly and efficiently.

```
Viper checks for the key in the following order:

1. Overrides Register (Aliases): This includes values set by viper.Set().
2. Flags
3. Environment variables
4. Config file: Even though the description mentions the config file, the values from the file are stored in memory and updated as needed (especially when using WatchConfig()). 
5. Key/value store
6. Defaults: Lastly, if the key is a flag and flagDefault is true, it will return the flag’s default value.
```

So, when you call ReadInConfig(), it literally reads the contents in file to a config variable in memory.

Your question is valid, but the impact on performance should be minimal.

Happy coding!

**Comment by LuSrackhall** [comment]
Thank you again for your reply!

Your response has given me a deeper understanding of Viper, which has been very helpful to me (otherwise, with my own clumsy verification method, it might have taken quite a bit of time).

In other words, when using Viper, there is no `disk I/O bottleneck` because of the memory buffering, it reads very quickly, and the issue I mentioned is just a slight overhead at the memory level, so there's no need to worry at all!!!

I guess this overlay design approach can also be helpful for writing, because this way, after using viper.Set() and then writing to the file, you can get the most precise changes and incrementally update the file!
> Maybe my understanding is wrong again, but it doesn't matter anymore. Because with your help, I have gained a further understanding of Viper, which is enough for me to start using it.

You have helped me again, thank you very much!
