### ISSUE TITLE
Casing issues maps in Hugo

### ISSUE THREAD

**Issue by bep** [spf13/viper#259]
The Hugo tests with the latest Viper fails for keys ala

https://github.com/spf13/hugo/blob/master/hugolib/hugo_sites_test.go#L735

Not sure what is happing, but we use `mapstructure.Decode` to read that blackfriday map into a struct  - and it used to work, but not now.

https://github.com/spf13/hugo/blob/766c82a6bbf4423a037beb2b1967f720080e4658/helpers/content.go#L86

/cc @benoitmasson

**Comment by bep** [comment]
Note: I guess this is what we want, so I'm not saying this is a bug -- I'll fix it on the Hugo side. Just wanted to open up for discussion so we are clear on the casing topic.

**Comment by benoitmasson** [comment]
I'm really sorry I don't have time for this now, but my (quick) guess is that `siteConfig` is a map where keys are lowercased (but wasn't it already the case before?), while `combinedParam` keys are camel-case.

I'd try to lowercase the keys in `combinedParam`, for a start, to ensure that these existing keys are overwritten...

**Comment by bep** [comment]
OK, I know how to fix it -- but I just wanted to discuss the new behavior and if it is correct. Not sure what the "new behaviour is", though.

**Comment by bep** [comment]
Never mind, I'll just fix it. https://github.com/spf13/hugo/issues/2581

**Comment by benoitmasson** [comment]
Haaa, ok :-)

Well, I'm not sure I'm qualified enough on the viper side to answer that question... But these two things:
- Viper is said to be case-insensitive
- (as you pointed out in your earlier patch) lower-casing everything in the maps is the best way to perform a constant-time case-insensitive lookup

make me think that the current implementation is a reasonable choice.

As for my personal opinion on this: since Viper claims to be case-insensitive, I think any solution is valid, but assuming, on the Hugo side, anything for the case of the sub-map retrieved with `GetStringMap()` seems rather optimistic to me.

Whether it is lower-cased, or keeps the case defined in the configuration (but then, what if some configuration value `strangeCase: 1` is overridden with `Set("sTRANGeCasE", 2)`?), I wouldn't assume anything and I would change the `NewBlackfriday()` function to make it work whatever the case of `siteConfig` keys may be... As you probably already did, lower-casing the keys of `combinedParams` and adding `combinedParam[strings.ToLower(key)] = value` inside the loop would do the trick.

**Comment by bep** [comment]
You are right -- I remember I blocked a "lower-cased" PR in Viper a year ago because it crashed Hugo horribly. But Hugo is now in a much better shape in the test department, so such a change is manageable -- and all in all better for the end users.
