### ISSUE TITLE
Can't read Windows file paths

### ISSUE THREAD

**Issue by KempWatson** [spf13/viper#278]
When processing a TOML file with a Windows file path such as MyVal = "C:\somepath”, ReadInConfig errors out due to the backslash. Forward slashes work, (escaped) double backslashes too. But a Windows user shouldn’t have to deal with UNIX paths or Go-specific escaping…

**Comment by moorereason** [comment]
Windows users still have to use valid TOML.  Read [the spec](https://github.com/toml-lang/toml#user-content-string).

**Comment by Simkiw** [comment]
Hi,  

I have the same issue on windows : `Config File "config.toml" Not Found in "[C:\\correct\\path\\to\\config\\directory]"`
Go can read files without any issue on windows, why can't i do it with viper as well?
```
        viper.SetConfigName("config.toml")
	// viper.SetConfigType("toml")

	viper.AddConfigPath(".")

	if err := viper.ReadInConfig(); err != nil {
		return err
	}
```
Or maybe it's supposed to be a package for linux only?  
(same behavior with `.json`, `.env`)

Cheers

**Comment by Simkiw** [comment]
Not really, it's actually working but the doc might be a bit misleading i have to say...  
Before i get into it : it does work on windows too :)  


So i've been experimenting a little bit with the package
```
func main() {
	viperENV := viper.New()
	if err := readEnvConfig(viperENV); err != nil {
		fmt.Println(err)
	}

	viperJSON := viper.New()
	if err := readJsonConfig(viperJSON); err != nil {
		fmt.Println(err)
	}

	viperTOML := viper.New()
	if err := readTomlConfig(viperTOML); err != nil {
		fmt.Println(err)
	}
}
```
I had 3 config files with the same name but different extension.  
The `config.env` was not recognized <=> while debugging, `.env` is not part of the viper list of supported extensions  

As for the other 2 : .json & .toml  
It was only parsing `json` no matter what.  
However, it did parse it when i moved the .json away in another directory.  
So i started debugging and it turned out viper was always reading `config.json` even if i did `SetConfigType("toml")`.   

I ended up using `SetConfigFile` which appears to solve the issue.  

```
	// vip.AddConfigPath(".")
	// vip.SetConfigName("config")
	// vip.SetConfigType("toml")
	vip.SetConfigFile("config.toml")
```

Now, i'm able to have 2 viper instances, one for json and the other for toml.  
I was not able to leverage the environment variable feature.  
If someone has spot the error in my code, please let me know.

Thank you,
