### ISSUE TITLE
Comments for value

### ISSUE THREAD

**Issue by zlepper** [spf13/viper#346]
As part of setting default values it would also be really lovely to be able to set comments on the attributes, so it's easier for whoever have to edit them, to know what they are, without having to lookup information outside their editor. 

I know this will not work with some formats (e.g. JSON), but other formats like yaml or toml supports comments, so it would be really lovely to have them available.

**Comment by scrouthtv** [comment]
Is there any update to this yet?

**Comment by sagikazarmark** [comment]
It would be infinitely hard to implement a feature like this. Every format supports comments differently:

- block comment vs line comment
- comment above a key or on the same line

It's not just hard to implement, but also hard to get it right and everyone would want it to work differently.

In my opinion, you are looking for a config schema "language" that can provide this kind of thing in a structured way:

- description for a config option
- validation rules
- etc

That would be incredibly useful, but haven't found one myself either. The closest thing I found is [CUE](https://cuelang.org/).

In any case, I don't think it's worth implementing this in Viper (for the above reasons), especially since all efforts are going into V2 now.

Thanks for suggesting anyway! Stay safe!
