### ISSUE TITLE
Complex JSON and Get() function

### ISSUE THREAD

**Issue by endorama** [spf13/viper#42]
Hello, I'm having some problem getting data from a nested JSON config file.

My JSON:
```json
{
  "types": [
    {
      "web": {
        "foo": "bar"
      }
    }
  ]
}
```

I need to get the `foo` key, so I thought I would do:
```go
x := viper.Get("types")
x[0]["web"]["foo"]
```
I thought I would also be able to iterate on `x` using `range` but this does not work due to a error:
```
invalid operation: x[0] (type interface {} does not support indexing)
```

To correctly get the value I need to write this:
```go
// this returns "bar"
viper.Get("types").([]interface{})[0].(map[string]interface{})["web"].(map[string]interface{})["foo"]
```

Any hint on how this could be improved? Is the intended behaviour? Am I totally missing something?

Thanks for the cool library ( and cobra and jww, I'm using them all :D )

**Comment by kzvezdarov** [comment]
It's because of the type system and the fact that Go is a statically typed language. Your JSON gets decoded to a `map[string]interface{}` because the values mapped to the keys can be anything - primitives, slices, maps, etc. You are required to assert the type since Go cannot do that on its own.
Unfortunately it is highly unlikely that this can be improved while retaining the flexibility[1], even with some dark reflection magics.

[1] You could declare the type structure of your configs ahead of time, with nested structs. This reduces the flexibility of your config though I'd argue that it is always good design to be able to statically specify the type structure of your expected configuration.

**Comment by endorama** [comment]
Thanks for the answer! Could you please provide and example of statically specifying the type structure?

**Comment by kzvezdarov** [comment]
Sure. It heavily depends on the configuration that you are trying to parse. In your case you can do this (though I assume your config is not as trivial as in the code snippet, which will result in a totally different structure):
```
type TypeInfo map[string]map[string]string

type TypeConfig struct {
    TypesList []TypeInfo `json,mapstructure:"types"`
}
```
Note the usage of struct flags. Struct flags are *very* useful, and make maintaining data structures which map to configuration very easy (minor changed in how a field is called in the JSON? Just change the struct tag and :shipit: ).

Another cool trick is to use struct embedding - just keep in mind that you need to add a mapstructure tag to flatten the embed.

Finally, I strongly recommend that you spend a lot of time planning out your config scheme. This is a thing for all languages and config systems, not just Go and Viper, but especially in statically typed languages it pays off to make sure you are not fighting the language to fit the config.

**Comment by endorama** [comment]
Thanks for your help! :) 

Closing
