### ISSUE TITLE
default value not apply to GetStringMapString

### ISSUE THREAD

**Issue by marionzheng** [spf13/viper#453]
codegen.toml

```toml
[codegen]
output_path = "../model/"
```

code

```golang
viper.SetDefault("codegen.output_path", "../model/auto/")
viper.SetDefault("codegen.sub_model_output_path", "ddd")
viper.SetConfigName("codegen")
viper.AddConfigPath("./templates")
err := viper.ReadInConfig()
if err != nil {
    panic(fmt.Errorf("Fatal error config file: %s \n", err))
}

codegenCnf := viper.GetStringMapString("codegen")
outputPath := codegenCnf["output_path"]
subModelOutputPath := codegenCnf["sub_model_output_path"]

fmt.Printf("%s", subModelOutputPath)
```

output "" not "ddd"

**Comment by marionzheng** [comment]
and this way also not work

```code
viper.SetDefault("codegen", map[string]string {
    "output_path": "../model/auto/",
    "sub_model_output_path": "eee",
})

codegenCnf := viper.GetStringMapString("codegen")
outputPath := codegenCnf["output_path"]
subModelOutputPath := codegenCnf["sub_model_output_path"]

fmt.Printf("%s", subModelOutputPath)
```

**Comment by neurocline** [comment]
This is because Viper doesn't really support merging at any level - keys or subkeys completely override data at higher level. You can see this in the Hugo source where there's code to merge in default values for Blackfriday with a subset declared in a config file (look at the function `newBlackfriday` in `github.com/gohugoio/hugo/helpers/content.go` to see what I'm talking about). I think this is also why Hugo does defaults last, whereas logically you'd do them first.

Personally, I find the Viper behavior awkward, but at the same time I can understand why they don't want to tackle merging - for every case where it goes right, there's a host of edge cases where it goes wrong.
