### ISSUE TITLE
Env variable does not set value for flag

### ISSUE THREAD

**Issue by estahn** [spf13/viper#461]
**Given:**
```golang
serverCmd.Flags().StringVar(&listeningAddress, "web.listen-address", ":9253", "...")
    
viper.BindEnv("foobar", "PHP_FPM_WEB_LISTEN_ADDRESS")
viper.BindPFlag("foobar", serverCmd.Flags().Lookup("web.listen-address"))
```

**Result:**

`listeningAddress` will still be `:9253` if i pass in `PHP_FPM_WEB_LISTEN_ADDRESS=":1234"`

**Expected**

`listeningAddress` containing the value `:1234`

**Comment by estahn** [comment]
My workaround for this is

```golang
	envs := map[string]string{
		"PHP_FPM_WEB_LISTEN_ADDRESS": "web.listen-address",
		"PHP_FPM_WEB_TELEMETRY_PATH": "web.telemetry-path",
	}

	for env, flag := range envs {
		if value := os.Getenv(env); value != "" {
			serverCmd.Flags().Lookup(flag).Value.Set(value)
		}
	}
``

**Comment by justinfx** [comment]
I've hit this same issue a year back, as well as again just now. Even though we use a bind function between viper and cobra, the environment variable value does not seem to drive the flag value. So this means you would have to check viper instead of cobra. Is the expected?

**Comment by sagikazarmark** [comment]
Not sure I understand this correctly, but flags always take precedence over env vars, so this behavior is expected.

**Comment by justinfx** [comment]
@sagikazarmark did you close this issue because you didn't understand it correctly? My experience is that its not a matter of both the flag and the env var being set and that the flag value wins. The issue I have observed is that with the flag completely unset, and the env var set, the env value does not propagate to the flag value in cobra even if there is a bind. 
What I would expect to see is that if we say to bind a cobra flag with viper, that viper would propagate the env var value to the flag. 
What I would currently see is that you end up not seeing the value if you look at cobra. You have to use viper to read the value. So is that the expected behaviour? That is, if a developer chooses to user viper and binding to cobra flags, then the application must not use cobra api to look up flag value. They must go through the viper api to ensure they see the value.

**Comment by sagikazarmark** [comment]
I think what you and the OP brought up are not the same issue. The example suggested that @estahn wanted env vars to take precedence (it didn't actually include how values were accessed in his case). The workaround showed something different again.

Viper doesn't actually know anything about Cobra, so this can't be solved on Viper's side.

So yeah, this is expected. If you want to use Viper for env vars, you need to use Viper's API to access configuration. Things might improve a bit with Viper 2 where the consumer will have much more control over Viper, so Cobra would be able to build better integrations. But that doesn't change the fact that this is a Cobra responsibility.

I've opened a discussion about Cobra integration: https://github.com/spf13/viper/discussions/1061

There are a number of workarounds by several users. Maybe those help.

I suggest opening an issue in the Cobra repository (but I'm pretty sure there are a bunch of open issues already).

**Comment by justinfx** [comment]
I re-read the OPs post and I think we are still talking about the same problem, but maybe the confusing detail is that the flag sets a default value. From what I read, the OP wants to declare a flag with some default value. And then when the value is only set via env var, that it would propagate to the cobra flag because of the bind. But the end result is that the bind is only one way, and that the flag use would drive the value in viper. So the workaround OP proposed is checking the env manually and pushing the value into the flag if it is set. 
So yea we are talking about the same situation. I would have expected "bind" to mean that its bi-directional. Thanks for the references though. I will follow up on that Cobra discussion.

**Comment by sagikazarmark** [comment]
Yeah, I could have misunderstood the issue then

**Comment by md2k** [comment]
I know that issue closed, but maybe it will be good for others:
in short if you want have Viper+Cobra works a way where Cobra flags has defaults, but if Env variable is set then Cobra flag took Env variable values you can do something like this:
```go
var (
	appName    string = filepath.Base(os.Args[0])
	configFile string = fmt.Sprintf("./%s.yaml", appName)
)

func init() {
	viper.SetEnvPrefix("TEST")
	viper.SetDefault("config", configFile)
	viper.AutomaticEnv()

	rootCmd.Flags().SortFlags = false
	rootCmd.PersistentFlags().SortFlags = false
	rootCmd.PersistentFlags().StringP("config", "c", viper.GetString("config"), "Location of config file.")
}

var rootCmd = &cobra.Command{
	Use:   appName,
	Short: "Server-Client agent to manage AEM inside containers.",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(cmd.Root().PersistentFlags().Lookup("config").Value.String())
	},
}
```
As result , default config file for example `my-app.yaml` if `--config|-c` not set, if `TEST_config` then config file will be set from Env variable value, if `--config|-c` added to command line arguments by user, then argument value will be used, because it have  higher priority over Viper in such flow.

P.S.: Maybe it will be nice to add such example to Viper or Cobra repo?

**Comment by ashleyconnor** [comment]
The example above can't be used with `MarkPersistentFlagRequired`.

Found a solution that works as I expect here: https://carolynvanslyck.com/blog/2020/08/sting-of-the-viper/
