### ISSUE TITLE
MergeInConfig overrides slices and maps

### ISSUE THREAD

**Issue by Viv1k** [spf13/viper#462]
Hi,

Viper is an awesome configuration tool. I am using it in a lot of projects.

Recently, I used MergeInConfig() to merge multiple config files as follows:
```
viper_config.SetConfigName(fname)
err = viper_config.MergeInConfig()
```

When you have slices or map in config than slice is overwritten by the last config file processed instead of appending.
Since we are merging here. Slices and Map should also be appended/merged. Am I correct here?
Please do let me know.

**Comment by bep** [comment]
> Slices and Map should also be appended/merged.

I think that would be very confusing. You cannot merge on that level without knowing the context.

**Comment by neurocline** [comment]
You could use multiple Vipers, then write your own merge code (call viper.AllSettings or viper.AllKeys to query a viper you're merging from). This has the benefit of not trying to fork the Viper repo.

I would love full merging myself, but I agree with @bep that there's no one-size-fits-all solution. It's a messy problem.

**Comment by neurocline** [comment]
Of course, now that I go to write such code as an example, I realize that without modifying Viper, this is a little painful; there's no way to write individual values to v.config, which is where config sources are held. You'd have to create the multiple config Vipers, then suck out their contents into maps, merge them, then turn it back into JSON/YAML/TOML/props, and read it in again to a new Viper. That's too much work. Maybe there's an easier way, because I would like a better way to merge default values and config values (the same problem exists, just across two levels of the viper sources hierarchy).

**Comment by john-deng** [comment]
+1
It would be helpful if MergeInConfig overrides slices and maps.

**Comment by Viv1k** [comment]
Closing this issue. 
User can use multiple vipers and can merge on their own.
