### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by hij1nx** [spf13/viper#58]
Because of a 404 on [`this dependency`](https://github.com/spf13/viper/blob/master/viper.go#L38) it is not possible to successfully install by running `go get github.com/spf13/viper`.

**Comment by kzvezdarov** [comment]
I'm able to `go get` both Viper and the dependency. Could you post the error output?

**Comment by hij1nx** [comment]
using `go version go1.4.2 darwin/amd64`. `go get` just hangs forever, so i installed each item in the import list by hand. Then the last one (on the line that i pointed out) i tried to `go get` and it started hanging again, so it turns out that url is a `404`. So since the url is a 404 on github is it possible you have a cached dependency?

**Comment by hij1nx** [comment]
Also, not sure if it helps but the 404 is on `github.com/xordataexchange/crypt/config` (and the code is actually here `github.com/xordataexchange/crypt/tree/master/config`).

**Comment by kzvezdarov** [comment]
That's just how GitHub URLs work - because `config` is part of the `crypt` repository, the URL includes the branch specification. Which is why `github.com/xordataexchange/crypt/config` 404s and  `github.com/xordataexchange/crypt/tree/master/config` doesn't - the first is the canonical import path, the second is the GitHub URL that links to the `config` folder in the `crypt` repository at the `master` branch.

I initially tested on a Linux machine with cleaned dependencies, I just tested it on an OS X machine with the versions that you specified above. I installed in a completely clean `GOPATH` - it takes a few minutes to download all the dependencies with my admittedly poor bandwidth, but worked nonetheless. I am thinking that this issue that you are seeing might be caused by a problem with your setup. Try to define a clean `GOPATH` somewhere else and `go get`  again.

**Comment by hij1nx** [comment]
I'm pretty sure i knew how github urls worked ;) I just installed go and this is one of the first go libs im installing. so... is there any other specific info i can give you?

**Comment by hij1nx** [comment]
Also, I've installed several other libs in the last few hours, they all work fine.

**Comment by kzvezdarov** [comment]
Right, what I was trying to explain is that it is expected that `github.com/xordataexchange/crypt/config` will 404, as it is the Go import path but not the actual URL for accessing it. Travis build re-run passed as well, so I am a bit baffled by this issue.

Could you create a clean Go environment and then post the output of `go get` with verbosity enabled e.g.:
```
mkdir $HOME/gotest
export GOPATH=$HOME/gotest

go get -v github.com/spf13/viper
```

Give it some time to run, it should time out and dump the stack trace eventually which should reveal the issue.

**Comment by hij1nx** [comment]
ah, ok so it was just taking an extraordinarily long time for some reason.

**Comment by hij1nx** [comment]
thx though :)
