### ISSUE TITLE
Default option when no key set in config after configuration reload

### ISSUE THREAD

**Issue by FZambia** [spf13/viper#61]
Hello, @spf13 !

I was implementing configuration reload on SIGHUP signal and came across an issue with default option value. When I am deleting key entirely from JSON config I expect that after reload value for this key will be set to default value, but it's not - the key still have previous value.

Here is an example:

```go
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/spf13/viper"
)

func main() {
	var jsonExample []byte

	viper.SetDefault("num", 5)
	viper.SetConfigFile("/tmp/example.json")

	jsonExample = []byte(`
	{
		"num": 3
	}
	`)
	ioutil.WriteFile("/tmp/example.json", jsonExample, 0644)
	viper.ReadInConfig()
	fmt.Println(viper.GetInt("num"))

	jsonExample = []byte(`
	{}
	`)
	ioutil.WriteFile("/tmp/example.json", jsonExample, 0644)
	viper.ReadInConfig()
	fmt.Println(viper.GetInt("num")) // expecting default value 5 here

	jsonExample = []byte(`
	{
		"num": 10
	}
	`)
	ioutil.WriteFile("/tmp/example.json", jsonExample, 0644)
	viper.ReadInConfig()
	fmt.Println(viper.GetInt("num"))
}
```

The output:
```bash
3
3
10
```

While I am expecting this:
```bash
3
5
10
```

?

**Comment by kzvezdarov** [comment]
I'll look into it more late today but at first glance it looks like during the file loading step values missing from the config file do not translate to the config register's corresponding key being removed. So the (now stale) key remains and since it has a higher priority than the defaults registry, that old config value gets returned instead.

**Comment by kzvezdarov** [comment]
Ok so the issue is here:

https://github.com/spf13/viper/blob/master/viper.go#L669

The `v.config` field does not get reset before reading in the configuration from file. This means that for all values not present in the file, the current values in `v.config` persist, and since they stay in existence, the defaults get overridden.

Working on a patch for that.

**Comment by kzvezdarov** [comment]
@FZambia #62 fixes the issue. Let me know if other issues related to your config reload appear.

**Comment by FZambia** [comment]
@kzvezdarov thank you very much!
