### ISSUE TITLE
how to  identify  .tml ?

### ISSUE THREAD

**Issue by gy0624ww** [spf13/viper#733]
.tml .toml are both belong to type toml config file.

but when set
`viper.SetConfigType("tml")`
show error : Config File "config" Not Found in ....

but adjustment the type to "toml", it works 
`viper.SetConfigType("toml")`

viper does not compatible with .tml?

**Comment by sagikazarmark** [comment]
No, `tml` extension is not supported as the [TOML specification explicitly says [.toml](https://github.com/toml-lang/toml#filename-extension) as an extension. Furthermore, nothing on the internet suggests that `tml` is actually used as a TOML file extension.

I suggest using `.toml` instead of `.tml`.
