### ISSUE TITLE
Configuration file per environment?

### ISSUE THREAD

**Issue by jpetitcolas** [spf13/viper#80]
Hi there,

I come from Node.js world, when we got the `config` module. This one allows to specify several configuration files, such as `default.json`, `development.json` and `production.json`. Depending of environment variable, we serve either dev or prod file, fallbacking on `default.json` for not specified values.

Can we achieve the same process with Viper?

I guess we can switch on correct configuration file using a test on environment variable and `viper.SetConfigName` method. But what about the fallback feature? Can we tell Viper to get them from a file instead of setting them manually via several `SetDefault` calls?

**Comment by ElliotReeve** [comment]
+1 for this - exactly what I am trying to do.

This could be done in the way @jpetitcolas has mentioned with different files or the framework Revel has implemented it in one file with [enviroments] defined - https://revel.github.io/manual/appconf.html

**Comment by didenko** [comment]
Would it make sense to wrap the `viper.New()` function in your application, so that the wrapper sets up the returned _`viper`_ object with correct paths, config name, etc. per parameters you feed to the wrapper?

Fallback, the way I understand it, may be trickier, but I am not sure I gather what you mean as fallback. Using `SetDefault(key string, value interface{})` while iterating over  `AllSettings() map[string]interface{}` to post settings read into one _`viper`_ object into another may be what you are looking for, but that is my assumption.

Regardless, I am not sure that function belongs to inside the library - it may or may not be common enough to warrant the inclusion - even assuming I correctly understood what you are trying to achieve.

**Comment by doublerebel** [comment]
I think the ability to set defaults from a file is important functionality, but it looks like this could be done with the recent MergeConfig functionality from #132.

Scoped configs are also desired in #148.  However, we can already scope configs with Viper's [sub-tree feature](https://github.com/spf13/viper#extract-sub-tree).  Is there an environment/scope use case that sub-tree doesn't cover?

**Comment by dolftax** [comment]
```
func init() {
	// Set viper path and read configuration
	viper.AddConfigPath(".")
	if os.Getenv("ENV") == "PRODUCTION" {
		viper.SetConfigName("config")
	} else {
		viper.SetConfigName("devconfig")
	}
	err := viper.ReadInConfig()

	log.Println(viper.GetString("server.port"))
	// Handle errors reading the config file
	if err != nil {
		log.Fatalln("Fatal error config file", err)
	}
}
```

I do this and have two files "config.toml" and "devconfig.toml"

**Comment by MaruthiVSM** [comment]
@jaipradeesh Thanks for the above example but I have not understood one thing. How os.Getenv("ENV") is returning different value per dev and production? When same code runs in dev and prod it must give different values. I am not getting that part. Response is appreciated. Thank you.

**Comment by jaipradeesh** [comment]
@MaruthiVSM You need to set the variable explicitly in the environment.

**Comment by affanshahid** [comment]
For anyone else trying to use viper in a manner similar to `node-config`: its very easily achievable with a couple of lines of viper code. [This](https://gist.github.com/affanshahid/ed2daff79f13aa61b427abeb894af937) will get most of the features that `node-config` provides.

**Comment by sagikazarmark** [comment]
Closing as there is a solution.

#1046 will probably improve the situation even further.
