### ISSUE TITLE
bindenv does not enable setting environment value via viper.Set

### ISSUE THREAD

**Issue by tkiraly** [spf13/viper#850]
```go
package main

import (
	"fmt"
	"os"

	"github.com/spf13/viper"
)

func main() {
	os.Setenv("ENV", "aaa")
	viper.BindEnv("viper", "ENV")

	fmt.Println("viper: "+viper.GetString("viper"))
	fmt.Println("env: "+os.Getenv("ENV"))
	os.Setenv("ENV", "bbb")
	fmt.Println("viper: "+viper.GetString("viper"))
	fmt.Println("env: "+os.Getenv("ENV"))
	viper.Set("viper", "ccc")
	fmt.Println("viper: "+viper.GetString("viper"))
	fmt.Println("env: "+os.Getenv("ENV"))
}
```

i would expect that the last two lines print both ccc, but this is not the case. Seems like viper.Set does not set environment values though the variable is bound to the given env value.

**Comment by sagikazarmark** [comment]
That's not really how Viper works. Viper collects configuration values from various sources and gives you a unified interface for accessing them.

There is config file writing in Viper, but that's incredibly buggy and not the primary feature of Viper.

This is the expected behavior and I don't think what you are asking really fits into Viper.
I wonder what your use case is though for setting environment variables from within the process.

**Comment by tkiraly** [comment]
thanks for your comments.

my use case: my main program expects parameters via environment variables and i want to fine tune the env variables with a separate software before the main program starts.

i assumed that "bindenv" is a two-way binding, now i know that it is not. thanks!

**Comment by sagikazarmark** [comment]
What do you use Viper for then?

If your program relies solely on environment variables, you probably don't need Viper.

If you want to bring in other sources as well (eg. flags or files), you will probably have to change your app to use Viper directly instead of environment variables.

Personally, I prefer neither of those though. I usually unmarshal config params into config structs and pass those structs to my application.

Anyway, I guess this is resolved.
